// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztubmvvcfsozvjuogmbf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0dWJtdnZjZnNvenZqdW9nbWJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MzE4MzAsImV4cCI6MjA2NjAwNzgzMH0.c6oudC6YhyDBxKwrmzP-aI-EpuFWJ-2QMATrtXaW-SE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);